version: '3.8'

services:
  web:
    build:
      context: ./app
      dockerfile: ./Dockerfile
      args:
        workdir_prefix: /usr/src
    command:
#      - /bin/sh
#      - -c
      - |
        python manage.py runserver 0.0.0.0:8000
    volumes:
#      - ./app/:/usr/src/app/
      - ${APP_PATH:-./app/}:/usr/src/app/
#      - type: bind
#        source: ./app
#        target: ${APP_PATH}
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=people_depot
      - POSTGRES_PASSWORD=people_depot
      - POSTGRES_DB=people_depot_dev

volumes:
  postgres_data:
