version: '3.8'

services:
  web:
    build:
      context: ./app
      dockerfile: ./Dockerfile
      args:
        workdir_prefix: /usr/src
    command:
#      - /bin/sh
#      - -c
      - |
        python manage.py runserver 0.0.0.0:8000
    volumes:
#      - ./app/:/usr/src/app/
      - ${APP_PATH:-./app/}:/usr/src/app/
#      - type: bind
#        source: ./app
#        target: ${APP_PATH}
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=people_depot
      - POSTGRES_PASSWORD=people_depot
      - POSTGRES_DB=people_depot_dev
  tools:
    # docker-compose up tools
    # docker-compose run tools sh -c "pre-commit run --all-files"
    # docker-compose run tools sh -c "pre-commit run --all-files check-django-migrations"
    image: pd-tools:local
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        wokdir_prefix: /usr/src
    privileged: true
    # docker-compose --profile tools up # starts the tools service
    # docker-compose up starts the services that don't have a profile
    profiles: ["tools"]
    volumes:
      - ./:/usr/src/project/
      - /run/user/1000/docker.sock:/var/run/docker.sock

volumes:
  postgres_data:
