# Generated by Django 4.0.7 on 2022-10-05 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_primary_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='linkedin_account',
            field=models.CharField(blank=True, help_text='Linkedin URL ending. 3-100 letters or numbers', max_length=100),
        ),
    ]
