# Generated by Django 4.2.11 on 2024-09-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_projectprogramareaxref"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="program_areas",
            field=models.ManyToManyField(
                db_table="project_program_area_xref", null=True, to="core.programarea"
            ),
        ),
        migrations.DeleteModel(
            name="ProjectProgramAreaXref",
        ),
    ]
