# Generated by Django 4.2.11 on 2024-09-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_project_program_areas_delete_projectprogramareaxref"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="program_areas",
            field=models.ManyToManyField(
                blank=True,
                db_table="project_program_area_xref",
                related_name="projects",
                to="core.programarea",
            ),
        ),
    ]
