# Generated by Django 4.2.11 on 2024-09-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_alter_project_program_areas"),
    ]

    operations = [
        migrations.RenameField(
            model_name="affiliate",
            old_name="partner_logo",
            new_name="logo",
        ),
        migrations.RenameField(
            model_name="affiliate",
            old_name="partner_name",
            new_name="name",
        ),
        migrations.AddField(
            model_name="project",
            name="affiliates",
            field=models.ManyToManyField(
                blank=True,
                related_name="projects",
                through="core.Affiliation",
                to="core.affiliate",
            ),
        ),
    ]
