# Generated by Django 4.2.11 on 2024-09-05 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_rename_gmail_user_email_gmail_and_more")
    ]

    operations = [
        migrations.RenameField(
            model_name="affiliate",
            old_name="partner_logo",
            new_name="logo",
        ),
        migrations.RenameField(
            model_name="affiliate",
            old_name="partner_name",
            new_name="name",
        ),
        migrations.AddField(
            model_name="project",
            name="affiliates",
            field=models.ManyToManyField(
                blank=True,
                related_name="projects",
                related_query_name="project",
                through="core.Affiliation",
                to="core.affiliate",
            ),
        ),
    ]
