# Generated by Django 4.2.30 on 2026-08-30 17:04

from django.db import migrations, models
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_practicearea_icon_practicearea_leadership_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='recurrence',
            field=recurrence.fields.RecurrenceField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='timezone',
            field=models.CharField(default='America/Los_Angeles', max_length=50),
        ),
        migrations.RunSQL(
            sql="ALTER TABLE core_event ALTER COLUMN start_time TYPE timestamp with time zone USING ('1970-01-01'::date + start_time);",
            reverse_sql="ALTER TABLE core_event ALTER COLUMN start_time TYPE time;",
        ),
    ]
